import { jobListingSchema, type JobListing } from "./job-schema";

const rawJobListings = [
  {
    slug: "remote-customer-support-specialist",
    title: "Remote Customer Support Specialist",
    company: "Northstar",
    location: "Remote",
    workplace: "remote",
    salaryMin: 48000,
    salaryMax: 62000,
    salaryLabel: "$48k-$62k",
    jobType: "full_time",
    industry: "support",
    experienceLevel: "entry",
    schedule: "daytime",
    benefits: ["healthcare", "pto", "remote_stipend"],
    visaStatus: "no_sponsorship_needed",
    postingAgeDays: 4,
    fitGoals: ["raise_income_fast", "stabilize_schedule"],
    fitSignals: [
      "raise_income_fast",
      "stabilize_schedule",
      "no_degree_pathway",
    ],
    summary: "Steady remote support role with a solid base salary and clear hours.",
  },
  {
    slug: "evening-medical-billing-coordinator",
    title: "Evening Medical Billing Coordinator",
    company: "Blue Mesa Health",
    location: "Phoenix, AZ",
    workplace: "hybrid",
    salaryMin: 42000,
    salaryMax: 54000,
    salaryLabel: "$42k-$54k",
    jobType: "full_time",
    industry: "healthcare_admin",
    experienceLevel: "entry",
    schedule: "evening",
    benefits: ["healthcare", "pto"],
    visaStatus: "unknown",
    postingAgeDays: 6,
    fitGoals: ["stabilize_schedule", "build_new_career_path"],
    fitSignals: [
      "stabilize_schedule",
      "caregiving_friendly",
      "build_new_career_path",
    ],
    summary: "Structured evening shift with admin experience that can branch into healthcare ops.",
  },
  {
    slug: "junior-payroll-operations-analyst",
    title: "Junior Payroll Operations Analyst",
    company: "LedgerLoop",
    location: "Denver, CO",
    workplace: "hybrid",
    salaryMin: 52000,
    salaryMax: 68000,
    salaryLabel: "$52k-$68k",
    jobType: "full_time",
    industry: "payroll",
    experienceLevel: "entry",
    schedule: "daytime",
    benefits: ["healthcare", "pto", "retirement"],
    visaStatus: "unknown",
    postingAgeDays: 3,
    fitGoals: ["raise_income_fast", "build_new_career_path"],
    fitSignals: [
      "raise_income_fast",
      "build_new_career_path",
      "no_degree_pathway",
    ],
    summary: "Operations-heavy payroll role with upward mobility into finance systems work.",
  },
  {
    slug: "weekend-bookkeeping-assistant",
    title: "Weekend Bookkeeping Assistant",
    company: "Pine & Paper",
    location: "Remote",
    workplace: "remote",
    salaryMin: 24000,
    salaryMax: 32000,
    salaryLabel: "$24k-$32k",
    jobType: "part_time",
    industry: "bookkeeping",
    experienceLevel: "entry",
    schedule: "weekend",
    benefits: ["remote_stipend"],
    visaStatus: "no_sponsorship_needed",
    postingAgeDays: 8,
    fitGoals: ["raise_income_fast"],
    fitSignals: ["second_job_friendly", "flexible_hours", "no_degree_pathway"],
    summary: "Part-time remote work suited for second-income support and bookkeeping exposure.",
  },
  {
    slug: "flex-shift-operations-coordinator",
    title: "Flex-Shift Operations Coordinator",
    company: "Parcel Current",
    location: "Austin, TX",
    workplace: "on_site",
    salaryMin: 39000,
    salaryMax: 51000,
    salaryLabel: "$39k-$51k",
    jobType: "full_time",
    industry: "operations",
    experienceLevel: "entry",
    schedule: "flexible",
    benefits: ["healthcare", "pto"],
    visaStatus: "unknown",
    postingAgeDays: 5,
    fitGoals: ["stabilize_schedule"],
    fitSignals: ["flexible_hours", "caregiving_friendly", "stabilize_schedule"],
    summary: "Predictable ops work with flexible shift options for households managing schedule strain.",
  },
] as const satisfies readonly JobListing[];

export const jobListings = rawJobListings.map((job) => jobListingSchema.parse(job));

export function listJobs() {
  return [...jobListings];
}

export function getJobBySlug(slug: string) {
  return jobListings.find((job) => job.slug === slug);
}
