export type LaunchCityOption = {
  value: string;
  label: string;
  regionLabel: string;
  countryCode: string;
  keywords: string[];
};

export const launchCityOptions: LaunchCityOption[] = [
  {
    value: "amsterdam_nl",
    label: "Amsterdam",
    regionLabel: "North Holland, Netherlands",
    countryCode: "NL",
    keywords: ["amsterdam", "netherlands", "holland"],
  },
  {
    value: "austin_us",
    label: "Austin",
    regionLabel: "Texas, United States",
    countryCode: "US",
    keywords: ["austin", "texas", "united states"],
  },
  {
    value: "berlin_de",
    label: "Berlin",
    regionLabel: "Berlin, Germany",
    countryCode: "DE",
    keywords: ["berlin", "germany"],
  },
  {
    value: "buenos_aires_ar",
    label: "Buenos Aires",
    regionLabel: "Autonomous City of Buenos Aires, Argentina",
    countryCode: "AR",
    keywords: ["buenos aires", "argentina"],
  },
  {
    value: "chicago_us",
    label: "Chicago",
    regionLabel: "Illinois, United States",
    countryCode: "US",
    keywords: ["chicago", "illinois", "united states"],
  },
  {
    value: "dubai_ae",
    label: "Dubai",
    regionLabel: "Dubai, United Arab Emirates",
    countryCode: "AE",
    keywords: ["dubai", "uae", "united arab emirates"],
  },
  {
    value: "dublin_ie",
    label: "Dublin",
    regionLabel: "Leinster, Ireland",
    countryCode: "IE",
    keywords: ["dublin", "ireland", "leinster"],
  },
  {
    value: "edinburgh_gb",
    label: "Edinburgh",
    regionLabel: "Scotland, United Kingdom",
    countryCode: "GB",
    keywords: ["edinburgh", "scotland", "united kingdom", "uk"],
  },
  {
    value: "london_gb",
    label: "London",
    regionLabel: "England, United Kingdom",
    countryCode: "GB",
    keywords: ["london", "england", "united kingdom", "uk"],
  },
  {
    value: "los_angeles_us",
    label: "Los Angeles",
    regionLabel: "California, United States",
    countryCode: "US",
    keywords: ["los angeles", "la", "california", "united states"],
  },
  {
    value: "madrid_es",
    label: "Madrid",
    regionLabel: "Community of Madrid, Spain",
    countryCode: "ES",
    keywords: ["madrid", "spain"],
  },
  {
    value: "manchester_gb",
    label: "Manchester",
    regionLabel: "England, United Kingdom",
    countryCode: "GB",
    keywords: ["manchester", "england", "united kingdom", "uk"],
  },
  {
    value: "melbourne_au",
    label: "Melbourne",
    regionLabel: "Victoria, Australia",
    countryCode: "AU",
    keywords: ["melbourne", "victoria", "australia"],
  },
  {
    value: "mexico_city_mx",
    label: "Mexico City",
    regionLabel: "Mexico City, Mexico",
    countryCode: "MX",
    keywords: ["mexico city", "cdmx", "mexico"],
  },
  {
    value: "montreal_ca",
    label: "Montreal",
    regionLabel: "Quebec, Canada",
    countryCode: "CA",
    keywords: ["montreal", "quebec", "canada"],
  },
  {
    value: "new_york_us",
    label: "New York",
    regionLabel: "New York, United States",
    countryCode: "US",
    keywords: ["new york", "nyc", "united states"],
  },
  {
    value: "paris_fr",
    label: "Paris",
    regionLabel: "Ile-de-France, France",
    countryCode: "FR",
    keywords: ["paris", "france"],
  },
  {
    value: "rome_it",
    label: "Rome",
    regionLabel: "Lazio, Italy",
    countryCode: "IT",
    keywords: ["rome", "roma", "italy"],
  },
  {
    value: "sao_paulo_br",
    label: "Sao Paulo",
    regionLabel: "Sao Paulo, Brazil",
    countryCode: "BR",
    keywords: ["sao paulo", "sao-paulo", "brazil"],
  },
  {
    value: "seattle_us",
    label: "Seattle",
    regionLabel: "Washington, United States",
    countryCode: "US",
    keywords: ["seattle", "washington", "united states"],
  },
  {
    value: "seoul_kr",
    label: "Seoul",
    regionLabel: "Seoul, South Korea",
    countryCode: "KR",
    keywords: ["seoul", "south korea", "korea"],
  },
  {
    value: "singapore_sg",
    label: "Singapore",
    regionLabel: "Singapore",
    countryCode: "SG",
    keywords: ["singapore"],
  },
  {
    value: "stockholm_se",
    label: "Stockholm",
    regionLabel: "Stockholm County, Sweden",
    countryCode: "SE",
    keywords: ["stockholm", "sweden"],
  },
  {
    value: "sydney_au",
    label: "Sydney",
    regionLabel: "New South Wales, Australia",
    countryCode: "AU",
    keywords: ["sydney", "new south wales", "australia"],
  },
  {
    value: "tokyo_jp",
    label: "Tokyo",
    regionLabel: "Tokyo, Japan",
    countryCode: "JP",
    keywords: ["tokyo", "japan"],
  },
  {
    value: "toronto_ca",
    label: "Toronto",
    regionLabel: "Ontario, Canada",
    countryCode: "CA",
    keywords: ["toronto", "ontario", "canada"],
  },
  {
    value: "vancouver_ca",
    label: "Vancouver",
    regionLabel: "British Columbia, Canada",
    countryCode: "CA",
    keywords: ["vancouver", "british columbia", "canada"],
  },
  {
    value: "warsaw_pl",
    label: "Warsaw",
    regionLabel: "Masovian Voivodeship, Poland",
    countryCode: "PL",
    keywords: ["warsaw", "poland"],
  },
  {
    value: "zurich_ch",
    label: "Zurich",
    regionLabel: "Zurich, Switzerland",
    countryCode: "CH",
    keywords: ["zurich", "switzerland"],
  },
  {
    value: "osaka_jp",
    label: "Osaka",
    regionLabel: "Osaka Prefecture, Japan",
    countryCode: "JP",
    keywords: ["osaka", "japan", "kansai"],
  },
  {
    value: "busan_kr",
    label: "Busan",
    regionLabel: "Busan, South Korea",
    countryCode: "KR",
    keywords: ["busan", "south korea", "korea"],
  },
  {
    value: "bangkok_th",
    label: "Bangkok",
    regionLabel: "Bangkok, Thailand",
    countryCode: "TH",
    keywords: ["bangkok", "thailand"],
  },
  {
    value: "chiang_mai_th",
    label: "Chiang Mai",
    regionLabel: "Chiang Mai, Thailand",
    countryCode: "TH",
    keywords: ["chiang mai", "thailand"],
  },
  {
    value: "manila_ph",
    label: "Manila",
    regionLabel: "Metro Manila, Philippines",
    countryCode: "PH",
    keywords: ["manila", "metro manila", "philippines"],
  },
  {
    value: "cebu_ph",
    label: "Cebu",
    regionLabel: "Cebu, Philippines",
    countryCode: "PH",
    keywords: ["cebu", "philippines"],
  },
  {
    value: "jakarta_id",
    label: "Jakarta",
    regionLabel: "Jakarta, Indonesia",
    countryCode: "ID",
    keywords: ["jakarta", "indonesia"],
  },
  {
    value: "bandung_id",
    label: "Bandung",
    regionLabel: "West Java, Indonesia",
    countryCode: "ID",
    keywords: ["bandung", "indonesia", "west java"],
  },
  {
    value: "kuala_lumpur_my",
    label: "Kuala Lumpur",
    regionLabel: "Federal Territory of Kuala Lumpur, Malaysia",
    countryCode: "MY",
    keywords: ["kuala lumpur", "kl", "malaysia"],
  },
  {
    value: "penang_my",
    label: "Penang",
    regionLabel: "Penang, Malaysia",
    countryCode: "MY",
    keywords: ["penang", "malaysia", "george town"],
  },
  {
    value: "ho_chi_minh_city_vn",
    label: "Ho Chi Minh City",
    regionLabel: "Ho Chi Minh City, Vietnam",
    countryCode: "VN",
    keywords: ["ho chi minh city", "saigon", "vietnam", "viet nam"],
  },
  {
    value: "hanoi_vn",
    label: "Hanoi",
    regionLabel: "Hanoi, Vietnam",
    countryCode: "VN",
    keywords: ["hanoi", "vietnam", "viet nam"],
  },
  {
    value: "mumbai_in",
    label: "Mumbai",
    regionLabel: "Maharashtra, India",
    countryCode: "IN",
    keywords: ["mumbai", "india", "maharashtra"],
  },
  {
    value: "bengaluru_in",
    label: "Bengaluru",
    regionLabel: "Karnataka, India",
    countryCode: "IN",
    keywords: ["bengaluru", "bangalore", "india", "karnataka"],
  },
  {
    value: "delhi_in",
    label: "Delhi",
    regionLabel: "Delhi, India",
    countryCode: "IN",
    keywords: ["delhi", "new delhi", "india"],
  },
  {
    value: "hyderabad_in",
    label: "Hyderabad",
    regionLabel: "Telangana, India",
    countryCode: "IN",
    keywords: ["hyderabad", "india", "telangana"],
  },
  {
    value: "hong_kong_hk",
    label: "Hong Kong",
    regionLabel: "Hong Kong",
    countryCode: "HK",
    keywords: ["hong kong", "hk"],
  },
  {
    value: "taipei_tw",
    label: "Taipei",
    regionLabel: "Taipei, Taiwan",
    countryCode: "TW",
    keywords: ["taipei", "taiwan"],
  },
];