import type { ProviderDefinition, ProviderId } from "./provider-types";

export const providerRegistry: Record<ProviderId, ProviderDefinition> = {
  claude: {
    id: "claude",
    label: "Claude",
    officialLoginUrl: "https://platform.claude.com/login",
    officialDocsUrl: "https://docs.anthropic.com",
    riskLevel: "medium",
    category: "ai",
    setupPath: "/settings/integrations/claude",
  },
  openai: {
    id: "openai",
    label: "OpenAI",
    officialLoginUrl: "https://platform.openai.com/login",
    officialDocsUrl: "https://platform.openai.com/docs",
    riskLevel: "medium",
    category: "ai",
    setupPath: "/settings/integrations/openai",
  },
  copilot: {
    id: "copilot",
    label: "GitHub Copilot",
    officialLoginUrl: "https://github.com/features/copilot",
    officialDocsUrl: "https://docs.github.com/en/copilot",
    riskLevel: "medium",
    category: "ai",
    setupPath: "/settings/integrations/copilot",
  },
  openclaw: {
    id: "openclaw",
    label: "OpenClaw",
    officialLoginUrl: "https://openclaw.ai/",
    officialDocsUrl: "https://openclaw.ai/",
    riskLevel: "high",
    category: "ai",
    setupPath: "/settings/integrations/openclaw",
  },
  gemini: {
    id: "gemini",
    label: "Gemini",
    officialLoginUrl:
      "https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Faistudio.google.com%2Fapi-keys",
    officialDocsUrl: "https://ai.google.dev/gemini-api/docs",
    riskLevel: "medium",
    category: "ai",
    setupPath: "/settings/integrations/gemini",
  },
  perplexity: {
    id: "perplexity",
    label: "Perplexity",
    officialLoginUrl: "https://console.perplexity.ai/",
    officialDocsUrl: "https://docs.perplexity.ai/",
    riskLevel: "medium",
    category: "ai",
    setupPath: "/settings/integrations/perplexity",
  },
  mistral: {
    id: "mistral",
    label: "Mistral",
    officialLoginUrl: "https://console.mistral.ai/",
    officialDocsUrl: "https://docs.mistral.ai/",
    riskLevel: "medium",
    category: "ai",
    setupPath: "/settings/integrations/mistral",
  },
  plaid: {
    id: "plaid",
    label: "Plaid",
    officialLoginUrl: "https://dashboard.plaid.com/signin",
    officialDocsUrl: "https://plaid.com/docs/",
    riskLevel: "medium",
    category: "banking",
  },
  wise: {
    id: "wise",
    label: "Wise",
    officialLoginUrl: "https://wise.com/login/",
    officialDocsUrl: "https://docs.wise.com/api-docs",
    riskLevel: "medium",
    category: "banking",
    setupPath: "/settings/integrations/wise",
  },
  revolut: {
    id: "revolut",
    label: "Revolut",
    officialLoginUrl: "https://developer.revolut.com/portal/signup",
    officialDocsUrl: "https://developer.revolut.com/docs/build-banking-apps",
    riskLevel: "medium",
    category: "banking",
    setupPath: "/settings/integrations/revolut",
  },
  vanguard: {
    id: "vanguard",
    label: "Vanguard",
    officialLoginUrl: "https://logon.vanguard.com/logon",
    officialDocsUrl:
      "https://investor.vanguard.com/investor-resources-education",
    riskLevel: "medium",
    category: "investing",
  },
  stripe: {
    id: "stripe",
    label: "Stripe",
    officialLoginUrl: "https://dashboard.stripe.com/login",
    officialDocsUrl: "https://docs.stripe.com/",
    riskLevel: "medium",
    category: "finance_ops",
  },
  ramp: {
    id: "ramp",
    label: "Ramp",
    officialLoginUrl: "https://app.ramp.com/sign-in",
    officialDocsUrl: "https://docs.ramp.com/",
    riskLevel: "medium",
    category: "finance_ops",
  },
  paypal: {
    id: "paypal",
    label: "PayPal",
    officialLoginUrl:
      "https://www.paypal.com/signin?returnUri=https%3A%2F%2Fdeveloper.paypal.com%2Fdashboard%2Fapplications%2Fsandbox&intent=developer",
    officialDocsUrl: "https://developer.paypal.com/docs/",
    riskLevel: "medium",
    category: "finance_ops",
    setupPath: "/settings/integrations/paypal",
  },
  gusto: {
    id: "gusto",
    label: "Gusto",
    officialLoginUrl: "https://app.gusto.com/login",
    officialDocsUrl: "https://docs.gusto.com/embedded-payroll",
    riskLevel: "medium",
    category: "payroll",
  },
  deel: {
    id: "deel",
    label: "Deel",
    officialLoginUrl: "https://app.deel.com/login",
    officialDocsUrl: "https://developer.deel.com/api/introduction",
    riskLevel: "medium",
    category: "payroll",
    setupPath: "/settings/integrations/deel",
  },
  quickbooks: {
    id: "quickbooks",
    label: "QuickBooks",
    officialLoginUrl: "https://accounts.intuit.com/",
    officialDocsUrl: "https://developer.intuit.com/app/developer/qbo/docs/learn/rest-api-features",
    riskLevel: "medium",
    category: "tax",
  },
  xero: {
    id: "xero",
    label: "Xero",
    officialLoginUrl: "https://developer.xero.com/app/manage",
    officialDocsUrl: "https://developer.xero.com/documentation/",
    riskLevel: "medium",
    category: "tax",
    setupPath: "/settings/integrations/xero",
  },
};
