import type { ProviderDefinition, ProviderId } from "./provider-types";

export const providerRegistry: Record<ProviderId, ProviderDefinition> = {
  claude: {
    id: "claude",
    label: "Claude",
    officialLoginUrl: "https://platform.claude.com/login",
    officialDocsUrl: "https://docs.anthropic.com",
    riskLevel: "medium",
    category: "ai",
    setupPath: "/settings/integrations/claude",
  },
  openai: {
    id: "openai",
    label: "OpenAI",
    officialLoginUrl: "https://platform.openai.com/login",
    officialDocsUrl: "https://platform.openai.com/docs",
    riskLevel: "medium",
    category: "ai",
    setupPath: "/settings/integrations/openai",
  },
  copilot: {
    id: "copilot",
    label: "GitHub Copilot",
    officialLoginUrl: "https://github.com/features/copilot",
    officialDocsUrl: "https://docs.github.com/en/copilot",
    riskLevel: "medium",
    category: "ai",
    setupPath: "/settings/integrations/copilot",
  },
  openclaw: {
    id: "openclaw",
    label: "OpenClaw",
    officialLoginUrl: "https://openclaw.ai/",
    officialDocsUrl: "https://openclaw.ai/",
    riskLevel: "high",
    category: "ai",
    setupPath: "/settings/integrations/openclaw",
  },
  plaid: {
    id: "plaid",
    label: "Plaid",
    officialLoginUrl: "https://dashboard.plaid.com/signin",
    officialDocsUrl: "https://plaid.com/docs/",
    riskLevel: "medium",
    category: "banking",
  },
  vanguard: {
    id: "vanguard",
    label: "Vanguard",
    officialLoginUrl: "https://logon.vanguard.com/logon",
    officialDocsUrl:
      "https://investor.vanguard.com/investor-resources-education",
    riskLevel: "medium",
    category: "investing",
  },
  stripe: {
    id: "stripe",
    label: "Stripe",
    officialLoginUrl: "https://dashboard.stripe.com/login",
    officialDocsUrl: "https://docs.stripe.com/",
    riskLevel: "medium",
    category: "finance_ops",
  },
  ramp: {
    id: "ramp",
    label: "Ramp",
    officialLoginUrl: "https://app.ramp.com/sign-in",
    officialDocsUrl: "https://docs.ramp.com/",
    riskLevel: "medium",
    category: "finance_ops",
  },
  gusto: {
    id: "gusto",
    label: "Gusto",
    officialLoginUrl: "https://app.gusto.com/login",
    officialDocsUrl: "https://docs.gusto.com/embedded-payroll",
    riskLevel: "medium",
    category: "payroll",
  },
  quickbooks: {
    id: "quickbooks",
    label: "QuickBooks",
    officialLoginUrl: "https://accounts.intuit.com/",
    officialDocsUrl: "https://developer.intuit.com/app/developer/qbo/docs/learn/rest-api-features",
    riskLevel: "medium",
    category: "tax",
  },
};
